# -*- coding: utf-8 -*-
"""Play Store App Review Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RW7BR7YVUXVYxVFpnk9aQy088S_3rctA

##Play Store App Review Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual
##### **Team Member 1 -**   Suraj Patil

# **Project Summary -**
The Play Store apps data has enormous potential to drive app-making
businesses to success. Actionable insights can be drawn for developers to
work on and capture the Android market. Each app (row) has values for
category, rating, size, and more. Another dataset contains customer reviews
of the android apps. Explore and analyse the data to discover key factors
responsible for app engagement and success.

Write the summary here within 500-600 words.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Do some analysis on playstore apps data so the android dveeloper could know in which catogory he/she should dvelop an app in order to reach maximum users and to make more profit out of it.

#### **Define Your Business Objective?**

--> Analysing the apps data which helps the sales team to discuss with the developing team so that the developing team can know which catogory apps has the potential to generate more profit and revenue for an organization.
--> Do some analysis to help the android developer to understand in which category apps where he/she should focus in order to make more profit.

Answer Here.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

drive.mount("/content/drive/")

"""### Dataset Loading"""

# Load Dataset
playstore_data=pd.read_csv("/content/drive/MyDrive/AlmaBetter_copies/Module-1/Capstone Project_EDA/Play Store Data.csv")
user_reviews=pd.read_csv("/content/drive/MyDrive/AlmaBetter_copies/Module-1/Capstone Project_EDA/User Reviews.csv")

"""### Dataset First View"""

# Dataset First Look
playstore_data.head(3)

user_reviews.head(2)

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
playstore_data.shape

user_reviews.shape

"""### Dataset Information"""

# Dataset Info
playstore_data.info()

user_reviews.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
playstore_data.duplicated().sum()

user_reviews.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
playstore_data.isna().sum()

user_reviews.isna().sum()

import missingno as msno

# Visualizing the missing values
msno.bar(playstore_data)

msno.bar(user_reviews)

"""### What did you know about your dataset?

Play Store data -->
The Play Store data contains 13 columns and 10841 rows. The App column represents the name of the app, category represents the app belongs to which category, Rating column represents out of 5 how much rating is given to respective app by user, Review represents how many users wrote the reviews for the respective app, size represents the size of the app in megabytes,installs represents how many users installed the app in their system, Type column represents the app is free or paid, price represents how much price is to be paid to use the app,Content Rating represents the who can use the app(the major market groupby age to be focus), Genres and Catogory columns are almost same it represents the genre of the app,Last updated represents the last date on which the developer team made some updates in the existing app,Current version represents the current version of the app and Android version represents the on and above android devices versions which can support the app to run in their environment.

User_review data--> This data set helps us to do sentiment analysis.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
app=playstore_data['App']
Category=playstore_data['Category']
Rating=playstore_data['Rating']
Reviews=playstore_data['Reviews']
Size=playstore_data['Size']
Installs=playstore_data['Installs']
Type=playstore_data['Type']
Price=playstore_data['Price']
ContentRating=playstore_data['Content Rating']
Genres=playstore_data['Genres']
LastUpdated=playstore_data['Last Updated']
CurrentVer=playstore_data['Current Ver']
AndroidVer=playstore_data['Android Ver']

# Dataset Describe
playstore_data.describe()

"""### Variables Description

App-> The names of apps                     
Category--> There are total 34 categories are there.         
Rating--> The rating is out of 5      
Reviews--> The user reviews       
Size--> Size of apps in KB and MB          
Installs--> The total number of installs     
Type--> Free and paid         
Price--> If paid then how much       
Content Rating--> General, above 18+, matured 17+, Teen     
Genres--> This and Category are same        
Last Updated, Current version, Android Version are not used in my
objective.
"""

print(playstore_data['App'].describe())
print("\n")
print(playstore_data['Category'].describe())
print("\n")
print(playstore_data['Rating'].describe())
print("\n")
print(playstore_data['Reviews'].describe())
print("\n")
print(playstore_data['Size'].describe())
print("\n")
print(playstore_data['Installs'].describe())
print("\n")
print(playstore_data['Type'].describe())
print("\n")
print(playstore_data['Price'].describe())
print("\n")
print(playstore_data['Content Rating'].describe())
print("\n")
print(playstore_data['Genres'].describe())
print("\n")
print(playstore_data['Last Updated'].describe())
print("\n")
print(playstore_data['Current Ver'].describe())
print("\n")
print(playstore_data['Android Ver'].describe())
print("\n")

"""### Check Unique Values for each variable."""

len(app)

# Check Unique Values for each variable.
app.unique()

Category.unique()

Rating.unique()

Reviews.unique()

Size.unique()

Installs.unique()

Type.unique()

Price.unique()

ContentRating.unique()

Genres.unique()

LastUpdated.unique()

CurrentVer.unique()

AndroidVer.unique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
playstore_data.head(3)

user_reviews.head(3)

merge_data=pd.merge(playstore_data,user_reviews)

merge_data.head(30)

merge_data.shape

merge_data.groupby("Category")['Rating'].median()

merge_data_by_cat_rat=merge_data.groupby("Category")['Rating'].median().reset_index().sort_values(by="Rating",ascending=False)

merge_data_by_cat_rat

merge_data_by_cat_rev=merge_data.groupby("Category")['Reviews'].median().reset_index().sort_values(by="Reviews",ascending=False)

merge_data_gen_rat=merge_data.groupby("Genres")['Rating'].median().reset_index().sort_values(by="Rating",ascending=False)

merge_data_gen_rat

merge_data.dtypes

merge_data['Installs']

merge_data['Installs']=merge_data['Installs'].str.replace("+","",regex=True)

merge_data['Installs']

merge_data['Installs']=merge_data["Installs"].str.replace(",","",regex=True)

merge_data["Installs"]

merge_data["Installs"]=merge_data["Installs"].astype(int)

type(merge_data["Installs"][0])

merge_data_installs=merge_data.groupby("Category")["Installs"].median().reset_index().sort_values(by="Installs",ascending=False)

merge_data_installs

merge_data.shape

merge_data.isna().sum()

merge_data.fillna(merge_data.mean(numeric_only=True).round(1),inplace=True)
string_columns=merge_data.select_dtypes(include=['object']).columns
merge_data[string_columns]=merge_data[string_columns].fillna(merge_data[string_columns].mode().iloc[0])

merge_data.isna().sum()

merge_data.head()

merge_data['Size'].replace("Varies with device",0,inplace=True)

merge_data['Size'].unique()

def value_to_float(x):
    if type(x) == float or type(x) == int:
        return x
    if 'k' in x:
        if len(x) > 0:
            return float(x.replace('k', '')) * 1000
        return 0
    if 'M' in x:
        if len(x) > 0:
            return float(x.replace('M', '')) * 1000000
        return 0
    return 0.0

merge_data['Size']=merge_data['Size'].apply(value_to_float)

merge_data['Size'].unique()

merge_data['Price']=merge_data['Price'].str.replace("$","",regex=True)

merge_data['Price']=merge_data['Price'].astype(float)

merge_data

"""### What all manipulations have you done and insights you found?

--> Here I grouped the neccessary columns and stored them in one DataFrame which I used further in this project for visualizations.    
--> I modified the Installs and Size columns in a way which can help us for do the analysis in a better way.     
--> Combined both the data sets so I can utilize them efficiently.
--> We can drop some columns here for ex:Sentiment because we can use Sentiment_Polarity instead of Sentiment for the better analysis. But I am not droping them.   
--> Here in the dataSets they are given Sentiment_Subjective column which means personnel opinions but I think we also need Sentiment_Objective also to know the factual information more.   
--> According to me Genres column also can be drop because we have Categorical column instead of Genres.Like vise we can drop Last Updated,	Current Ver,	Android Ver, Translated_Review columns also because those columns doesnt matter much. We have other major columns so we can use them instead of these columns I am going to drop them after discuss with some experts.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

merge_data.hist(bins=30, figsize=(15, 10))

"""1. Why did you pick the specific chart?                   
I picked this chart basically to know is my data is balanced or not if the data is not balanced then we need to make it balanced.(I am at my first module to make the data balance I think I need to go further into the course)

2.What is/are the insight(s) found from the chart?                
--> From the chart you can see that Rating data column is  right-skewed      
-->Size is  left-skewed                  
-->Installs is  left-skewed             
-->Price is  left-skewed                        
-->Sentiment_Polarity is  little bit right-skewed                    
-->Sentiment_Subjectivity is  little bit left-skewed

These 2 functions are used to put labels on the data which have been visualized
"""

# plt.rcParams['figure.figsize'] = (10, 5)
def addlabels_line(x,y):
    for i in range(len(x)):
        plt.text(i, y[i], y[i], ha = 'center')
        # plt.plot(y, marker = 'o', ms = 20, mec = 'r')
def addlabels_bar(x,y):
    for i in range(20):
        plt.text(i, y[i]//2, y[i], ha = 'center')

"""Chart- 2: Top and Last 20 most common Genres apps count"""

len(merge_data["Genres"].unique())

"""Note: Open all the visualization on seperate tabs so we can understand clearly what I am going to explain."""

plt.rcParams['figure.figsize'] = (60, 30)
plt.subplot(2,1,1)
plt.plot(merge_data["Genres"].value_counts()[:20], marker = 'o', ms = 20, color = 'orange')
plt.title("Top 20 same Genre app count")
plt.show()

plt.subplot(2,1,2)
plt.plot(merge_data["Genres"].value_counts()[54:74],marker = 'o', ms = 20, color = 'green')
plt.title("Last 20 same Genre app count")
plt.show()

"""1.Why did you pick the specific chart?                 
--> Here I want to know about the Top 20 and last 20 most common Genres apps count thats why I plotted the above graph.

2. What is/are the insight(s) found from the chart?                       
--> From above graph we can see that Sports, Action,Health and Fitness genre category app, etc in subplot(2,1,1) have maximum counts it means these genre category apps developed more.                          
--> And if we see the last 20 same Genre app count in subplot(2,1,2) Puzzle;Action & Adventure, Parenting;Music & Video,etc are have less apps in the market.

3. Will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.                                       

--> If any organization wants to compete with other organization in the app development sector then they need to care about these top 20 genre catogory apps because in the app market there are many common apps are there in these genre catogories compared to other genre category apps.                     
--> And if we see the last 20 same Genre app count in subplot(2,1,2) there Puzzle;Action & Adventure, Parenting;Music & Video,etc are have less apps in the market. so if any organization wants to make more profit then by developing some unique apps in these categories apps they can make.

Chart-3: Top 20 Category v/s Ratings
"""

# Chart - 3 visualization code
plt.figure(figsize=(55,15))
plt.bar(merge_data_by_cat_rat['Category'][:20],merge_data_by_cat_rat['Rating'][:20],color=['orange','yellow','green'])
addlabels_bar(merge_data_by_cat_rat['Category'], merge_data_by_cat_rat['Rating'])
plt.xlabel("Category")
plt.ylabel("Rating")
plt.grid()
plt.title("Category v/s Ratings")

"""1. Why did you pick the specific chart?

--> The bar chart can able to showcase which category top 20 apps the people likes most.

2. What is/are the insight(s) found from the chart?

--> I plotted Category v/s Ratings so we can understand whaich types of apps the people likes the most based on their user ratings.            
--> From above bar chart we can see the HEALTH_AND_FITNESS, Weather amd VEHICLE_AND_AUTO category apps got 4.6,4.4 and 4.3 user ratings.

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> If the developer build any HEALTH_AND_FITNESS category apps then there is a less probability that the app can get bad user ratings but thats not mean that we can make more profit out of it because there is a probality that there are less installs of the app but the app is very good and majority of the installers gave good ratings for the app. If we want to reach more users then we need to analyse the data in depth, only Ratings and Category are not sufficient to take decisions.    
--> From the graph we can see that HEALTH_AND_FITNESS,WEATHER, VEHICLE_AND_AUTO and GAME,etc category apps got some good ratings so if any organization wants to make good impression of them infront of the glob and want to take less risk of failure of the apps then they can focus on these category apps.     
--> If you see the less rated apps like Entertainment, Dating, Social then there might be a possiblity that some people created fake profile of them to trouble/harash the other users and the users who got harashed they provided bad ratings for the app. We need to more deep dive into the data to know where we need to focus in order to make more profit.

#### Chart - 4: Category v/s Reviews(Top 20 most reviewed apps)
"""

plt.figure(figsize=(50,25))
plt.subplot(2,1,1)
plt.bar(merge_data_by_cat_rev['Category'][:20],merge_data_by_cat_rev['Reviews'][:20],color = ['red', 'green'])
addlabels_bar(merge_data_by_cat_rev['Category'], merge_data_by_cat_rev['Reviews'])
plt.xlabel("Category")
plt.ylabel("Reviews")
plt.title("Top 20 most reviewed apps")
plt.grid()


plt.figure(figsize=(50,25))
plt.subplot(2,1,2)
plt.bar(merge_data_by_cat_rev['Category'][20:34],merge_data_by_cat_rev['Reviews'][20:34],color = ['red', 'green'])
plt.xlabel("Category")
plt.ylabel("Reviews")
plt.title("Least most reviewed apps")
plt.grid()

"""1. Why did you pick the specific chart?

--> Here I pick the above bar chart in order to understand which category Top 20 apps has the potential to produce more profit for an organisation.

2. What is/are the insight(s) found from the chart?

--> Here I plotted Category v/s Review which is able to tell which category apps has the potential to produce more profit for an organization.   
--> The Social, Photography, Game category apps are the top three reviewd app according to the data sets which means majority of the app users searched these category apps in the playstore.     
--> Like wise Dating, Art_and_design, Parenting, Beauty, Events, Comics, Medical apps have less reviews because if we see Dating apps then the market will be filtered because we need to fix one age limit to use the Dating apps and the app will be used by young generation(17 year-35 year).
And people prefer to draw and design by their hands personally for that they doesnt Art_and_design apps to make drawings and do other hobby related activities, for example we generally use paint app rarely.
For Parenting, Beauty apps peoples are less interesetd. And people prefer to personnaly visit the hospital and discuss their illness instead of visiting some apps.

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> If any organization wants to reach out more users and wants to make more profit out of them then they need to more focus on Social, Photography, Game category apps because people search these apps in the playstore more than other apps.     
--> The Medical, Comics, Events, other apps which has less Reviews are not able to generate more revenue in majority cases. Therefore if any organization wants to make more profit and wants less risk then they need to focus on more reviewd categorical apps.

#### Chart - 5 Top 20 Most installed Category apps
"""

merge_data_siz_ins=merge_data.groupby("Size")['Installs'].median().reset_index().sort_values(by="Installs")

install_price=merge_data.groupby("Category")["Installs"].median().reset_index().sort_values(by="Installs",ascending=False)
plt.figure(figsize=(55,25))
plt.subplot(2,1,1)
plt.bar(install_price['Category'][:20],install_price['Installs'][:20],color = ['green', 'orange'])

# x-axis label
plt.xlabel('Category')
# frequency label
plt.ylabel('Installs')
# plot title
plt.title('Category v/s Installs')
# showing legend
plt.legend()
plt.grid()
# function to show the plot
plt.show()


plt.figure(figsize=(55,25))
plt.subplot(2,1,2)
plt.plot(install_price['Category'][20:34],install_price['Installs'][20:34],linewidth=2,linestyle='dashed',color='green',markerfacecolor='blue',markersize=12, marker ='o')
# addlabels_line(install_price['Category'], install_price['Installs'])
plt.grid()
plt.show()

"""##### 1. Why did you pick the specific chart?

--> Above I plotted Category v/s Installs chart from which we can understand which category apps got installed more in devices. To understand which category apps should built in order to make more profit.

##### 2. What is/are the insight(s) found from the chart?

--> From the above charts we can easily say that the Photography, Productivity and Social apps are installed more compared to other category apps, it means in market if we want to reach more users and make more profit out of it then the developers and the organization need to focus on these category apps.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> I had plotted one Category v/s Review before the Category v/s Installed chart from the two charts we can observe that Social followed by Photography and Game category apps are Reviewed more but when it comes to installation Photography, Productivity, Social apps are installed almost equally followed by Game, Weather and other apps it means Social, Photography category apps installed and reviewed more but the Game apps reviewed more but when it comes to installation of the apps then dpend upon the Size of the apps it varies.    
-->The Productivity category apps are reviewed less but installed more it means the installation rate is more for Productivity category apps.

#### Chart - 6: Top 15 installed categorical apps acquisition in percentage
"""

# Chart - 4 visualization code
colors = ['r', 'y', 'g', 'b','#A2C3DB','#8871A0','#8AAF22','#DCB12D','#3F9F9F']

# plotting the pie chart
plt.pie(merge_data_installs['Installs'][:15], labels = merge_data_installs['Category'][:15], colors=colors,
        startangle=90, shadow = True,
        radius = 1, autopct = '%1.1f%%')

# plotting legend
plt.legend()
# showing the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

--> To know in Top 15 out of 100 % which category apps have occupied the majority of the market.

##### 2. What is/are the insight(s) found from the chart?

--> From above pie chart we can see that almost 77-78% are occuppied by Productivity, Social, Photography and Games category apps and remaining 22-23% market is occupied by weather,Video_Players and other category apps.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> From above pie chart we can see that almost 77-78% are occuppied by Productivity, Social, Photography and Games category apps and remaining 22-23% market is occupied by other category apps.     
--> If any organization wants to enter into the app business then they should focus on these 4 category apps to make more profit out of it. Where is a requirement there is a business.      
--> If anybody or any organization wants to build any other category apps then they needs to more focus on the uniqueness of the app because the majority market needs Productivity, Social, Photography and Games category apps.

#### Chart - 7: Category v/s Content Rating
"""

cat_install_price=merge_data.groupby(["Category","Content Rating"])["Installs"].median().reset_index().sort_values(by="Installs",ascending=False)

cat_install_price

plt.figure(figsize=(75,15))
plt.subplot(1,2,1)
plt.bar(cat_install_price["Category"][:20],cat_install_price['Installs'][:20],color = ['#8AAF22'])

# x-axis label
plt.xlabel('Category')
# frequency label
plt.ylabel('Installs')
# plot title
plt.title('Category v/s Installs')
# showing legend
plt.legend()
plt.grid()
# function to show the plot
plt.show()

plt.figure(figsize=(35,5))
plt.subplot(1,2,2)
plt.bar(cat_install_price["Content Rating"],cat_install_price['Installs'],color = ['#8AAF22'])

# x-axis label
plt.xlabel('Content Rating')
# frequency label
plt.ylabel('Installs')
# plot title
plt.title('Content Rating v/s Installs')
# showing legend
plt.legend()
plt.grid()
# function to show the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

--> Here I subplotted two graphs together to understand which age group people uses the apps most.

##### 2. What is/are the insight(s) found from the chart?

--> From above graph we can see that Teen aged people uses all category app most and if any organization targets the Adults only 18+ then there is limitted market to focus because majority of the apps will be used by Teen aged people.       
--> Therefore if any organization wants to develop an app in order to target only 18+ then they need to build the app unique to gain more profit.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> From above graph we can see that Teen aged people uses all category app most and if any organization targets the Adults only 18+ then there is limitted market to focus because majority of the apps will be used by Teen aged people.            
--> Therefore if any organization wants to develop an app in order to target only 18+ then they need to build the app unique to gain more profit.   
--> In market there are many apps are there which targets 18+ and they are making profit becuase there is some uniqueness in their apps and any organization wants to build app to target 18+ then they need to focus and try to find out the needs of the market.
"""

merge_data.head(30)

"""#### Chart - 8: Which apps reviews are more given on users sentiments:        
######Category v/s Sentiment_Polariry
"""

merge_data_sentiment=merge_data.groupby("Category")["Sentiment_Polarity"].median().reset_index().sort_values(by="Sentiment_Polarity",ascending=False)
merge_data_sentiment

plt.figure(figsize=(40,10))
plt.subplot(2,2,1)
plt.bar(merge_data_sentiment["Category"][:15],merge_data_sentiment["Sentiment_Polarity"][:15],color=["Orange"])
# addlabels_bar(merge_data_sentiment['Category'], merge_data_sentiment['Sentiment_Polarity'])
plt.xlabel("Category")
plt.ylabel("Sentiment_Polarity")
plt.title("Category vs Sentiment_Polarity")
plt.grid()



plt.figure(figsize=(40,10))
plt.subplot(2,2,2)
plt.bar(merge_data_sentiment["Category"][20:34],merge_data_sentiment["Sentiment_Polarity"][20:34],color=["Orange"])
# addlabels_bar(merge_data_sentiment['Category'], merge_data_sentiment['Sentiment_Polarity'])
plt.xlabel("Category")
plt.ylabel("Sentiment_Polarity")
plt.title("Category vs Sentiment_Polarity")
plt.grid()

plt.figure(figsize=(40,10))
plt.subplot(2,2,3)
plt.plot(merge_data_sentiment["Category"],merge_data_sentiment["Sentiment_Polarity"])
# addlabels_bar(merge_data_sentiment['Category'], merge_data_sentiment['Sentiment_Polarity'])
plt.xlabel("Category")
plt.ylabel("Sentiment_Polarity")
plt.title("Category vs Sentiment_Polarity")
plt.grid()

"""##### 1. Why did you pick the specific chart?

--> Here I plotted category v/s Sentiment polarity.    
--> This will help us to know which category apps have more bad reviews and we can predict why the reviews are bad for those category apps.

##### 2. What is/are the insight(s) found from the chart?

--> If sentiment polarity is bigger then that category apps has more positive review, the users are happy from those category of apps.   
--> We can see that all categories apps have almost similar sentiment_polarities but the Game category apps have less sentiment_polarity.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> All category apps have almost same sentiment_ploarity and the Gaming apps have less sentiment_ploarity compared to othe categories.        
--> If any organization wants to build gaming apps then they need to more focus on the users sentiments.        
--> If we want make more profit out of gaming apps then we might need to make and follow some rules in order to not hurt the user sentiments.

#### Chart - 9: category v/s sentiment subjectivity
"""

merge_data_sentiment_subjectivity=merge_data.groupby("Category")["Sentiment_Subjectivity"].median().reset_index().sort_values(by="Sentiment_Subjectivity")

merge_data_sentiment_subjectivity

plt.figure(figsize=(40,10))
plt.subplot(2,1,1)
plt.bar(merge_data_sentiment_subjectivity["Category"],merge_data_sentiment_subjectivity["Sentiment_Subjectivity"],color=["Orange"])
# addlabels_bar(merge_data_sentiment['Category'], merge_data_sentiment['Sentiment_Subjectivity'])
plt.xlabel("Category")
plt.ylabel("Sentiment_Subjectivity")
plt.title("Category vs Sentiment_Subjectivity")
plt.grid()

"""##### 1. Why did you pick the specific chart?

--> There are 2 types of reviews         
-----> Reviews based on sentiments          
-----> Reviews based on Factual data          
I want to know about on what basis the users given most of the reviews.

##### 2. What is/are the insight(s) found from the chart?

--> If you see the above graph Category v/s Sentiment_Subjectivity we can see that all th category apps have sentiment_subjectivity same.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> If you see the above graph Category v/s Sentiment_Subjectivity we can see that all th category apps have sentiment_subjectivity same but just consider if Weather, Art and Design followed by Game, Health and fitness have Sentiment_Subjectivity more it means most of the users given reviews based on sentiments which means if any organization needs to build the apps which are related to these categories then they need to more focus on the sentiments of the users.                           
--> They needed to think more about the sentiments of the people before creating these apps.

#### Chart - 10
"""

width1 = 0.5

merge_data_sentiment_subjectivity_polarity=merge_data.groupby("Category")[["Sentiment_Subjectivity","Sentiment_Polarity"]].median().reset_index().sort_values(by="Sentiment_Polarity")

merge_data_sentiment_subjectivity_polarity

# plt.bar(merge_data_sentiment_subjectivity["Category"],merge_data_sentiment_subjectivity["Sentiment_Subjectivity"],color=["Orange"])
plt.figure(figsize=(40,10))
plt.grid()
plt.bar(np.arange(len(merge_data_sentiment_subjectivity_polarity["Category"]))-0.2,merge_data_sentiment_subjectivity_polarity["Sentiment_Subjectivity"],0.4,color='r')
plt.bar(np.arange(len(merge_data_sentiment_subjectivity_polarity["Category"]))+0.2,merge_data_sentiment_subjectivity_polarity["Sentiment_Polarity"],0.4,color='g')

"""##### 1. Why did you pick the specific chart?

To know the relation between sentiment_subjectivity and sentiment_polrity.

##### 2. What is/are the insight(s) found from the chart?

Sentiment Subjectivity is directly proportional to Sentiment Polarity.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Sentiment Subjectivity is directly proportional to Sentiment Polarity.
--> The developer needs to care about the sentiments of the users before building any category apps specially gaming apps.

#### Chart - 11
"""

merge_data_price=merge_data.groupby("Category")["Price"].max().reset_index().sort_values(by="Price",ascending=False)
merge_data_price

plt.figure(figsize=(20,5))
plt.bar(merge_data_price["Category"][:15],merge_data_price["Price"][:15])
plt.grid()
plt.title("Category v/s Max Price")
plt.xlabel("Category")
plt.ylabel("Max_Price")

"""##### 1. Why did you pick the specific chart?

--> To know the max amount that the each category apps charge.

##### 2. What is/are the insight(s) found from the chart?

--> The Medical category apps charges the heighest amount and Sports, Personalization, Game, Dating, Family, Photography category apps charges 29.99,23,9.99,14,6.99,7,6.99,11,3.99,24,3.95 respectively.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> The medical category apps charges more because there are many reasons are there one of the reason might be expertise. For Medical category related apps we need more expertise.                             
--> The Sports, Game, Dating, Family apps also charges because the users are ready to pay and use those apps.                                    
--> And if we want to make more money then we need focus on these category apps.

#### Chart - 12
"""

# plt.bar(merge_data_sentiment_subjectivity["Category"],merge_data_sentiment_subjectivity["Sentiment_Subjectivity"],color=["Orange"])
plt.figure(figsize=(20,7))
plt.bar(merge_data_price["Category"][:15],merge_data_price["Price"][:15])
plt.grid()
plt.title("Category v/s Max Price")
plt.xlabel("Category")
plt.ylabel("Max_Price")
plt.figure(figsize=(20,7))
plt.grid()
plt.subplot(2,1,2)
plt.bar(merge_data_sentiment_subjectivity_polarity["Category"][:15],merge_data_installs["Installs"][:15],color='g')
plt.title("Category v/s Installs")
plt.xlabel("Category")
plt.ylabel("Installs")
plt.grid()

"""##### 1. Why did you pick the specific chart?

To check which paid app installed more.

##### 2. What is/are the insight(s) found from the chart?

--> We can see that in the graph the Gaming apps are installed more among the paying apps.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

--> We can see that in the graph the Gaming apps are installed more among the paying apps.                  
--> So If any organization planning to build any paid apps then they should build Gaming apps because from the data we can see that only Gaming apps are installed more among all other paying apps like Medical, Sports and all.

#### Chart - 13 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
merge_data.corr()

sns.heatmap(merge_data.corr()  , cmap="RdBu",vmin=0,vmax=1, annot=True,annot_kws={"fontsize":31,"fontweight":'bold'},square=True)

"""##### 1. Why did you pick the specific chart?

--> Heat map are used to understand the relation between various columns.
--> Relation interms of directly proportional or inverse proportional.

##### 2. What is/are the insight(s) found from the chart?

--> From the heat map we can see that Rating is not much depend on any other column variables.                                 
--> Blue color box represents the direct proportinality and red color box represents the inverse proportionality relation.                    
--> Rating and Price are inversely proportional to each other it means if Ratings are more then Price is less and vice versa.                     
--> If you take the Installs column then its inversely proportional to all other columns.                                
--> Sentiment Polarity and Sentiment Subjectivity are directly proportional to each other.

3. Will the gained insights help creating a positive business impact?

--> Sentiment Polarity is directly proportional to the Sentiment Subjectivity which means if any organization built some apps which may hurt the sentiments of the users then both sentiment polarity aswell as sentiment subjectivity varies in a similar manner.                
--> Rating and Price are inversely proportional to each other which means if any app got very good ratings then the app might be free or less priced.                                     
--> Size and installs are inversely proportional to each other which means if any developer built app of larger size then installs might very less for those apps therefore the developer need to focus on size of the apps aswell.                           
--> Installs and Snetiment polarity and Sentiment subjectivity are inversely proportional which means if installs are more then for those categoty apps the Sentiment polarity and sentiment subjectivity are might be less.

#### Chart - 1t - Pair Plot
"""

merge_data.columns

# Pair Plot visualization code
sns.set_style("whitegrid")
# merge_data_n=pd.DataFrame("merge_data",columns=merge_data.columns)
sns.pairplot(merge_data)

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

My suggestions would be completely based on the client business objective.
I had plotted many charts in order to explain how any organization or client can become success in app making business.  

There might be several business objecive of the clients for ex:    

--> The client might want to setup and build their name in the app making business by reaching out to more customers/users:

My Suggestion:

If we consider that the dveloper wants to make good name  of their organization then they need to more focus on free apps because if you see chart 11: in Category v/s Price chart Medical, Sports, Personalization, Game these category apps charges more compared to other category apps but their installs are very less you can see in chart5: Category v/s Installs. And if you see Category v/s Installs Photography, Productivity, Social and Game category apps installed more and they are free apps.

Here one question arises why any organization wants to build only their name and not money and the answer is if any business wants to grow for long term then they need to give some free services to make good name in the market like at the starting Reliance Jio gave free data services to its users for almost 1-1.5 years after making more users they charged them with similar price like other competitor (Airtel,VI,etc) does. After reaching out to more users we can charge them with a good amount.

--> The client might want to make only profit in the app market, they are thinking in terms of short period:
Suggestion:
If you see the most installed apps are free and if the client wants to earn more profit then they need to focus on paid apps like Medical, Sports and other category apps but here the installs might be less for these category apps because if you consider the Medical category apps in chart 5 the installs are very less because there might be several reasons for ex: People believes the offline market means they more trust in go and meet personally to the doctors and consultants compared to all other online apps. In these case we need to see the requirement of the users for ex: Traya found out that in India there are majority of the mens and womens facing hairfall issue they used this as a opportunity to sell their products they made their own mobile app and web apps. Basically if any organization wants to build any paid apps they need to focus on Medical,Sports, Game these category apps but they need a product so they can sell via these apps. If you consider Gaming apps then here I am taking example of BGMI(PUBG) they are providing the free service means user can play this game free but their main goal is to sell the avataar and other materials like wearables to the avataar from which the user can enjoy the game more.
                       
--> The client might want to achieve both. They want to build their name in the app market by reaching out to more users and after that they want to earn profit from them.   

Suggestion:
--> Almost 73-79 % of the market is acqired by Game:15.8%,social: 21.1%,Productivity: 21.1%, Photography: 21.1%  see chart 6, which means if the client wants to make more profit in the app making business then they should focus on these category apps.
--> To reach out to more users they initially need to provide some free good services. If you take example of BGMI(PUBG) gaming app they are gaving free services to users means the user can play this app free.
--> To make more profit out of the business they need to crate requiremnt of the service as BGMI(PUBG) created like most of the teenagers(Chart 7) use BGMI more. After creating requirement they need to find out many small unique source of income related to the free main service like in BGMI(PUBG) the main service is free but they are charging the money if the user wants to more enjoy the game for ex: They are charging for avataars and the wearables for that avataar. If the user wants to feel and enjoy the game he/she needs to buy the vouchers and spend them on other materials related to game.

# **Conclusion**

--> Almost 73-79 % of the market is acqired by Game:15.8%,social: 21.1%,Productivity: 21.1%, Photography: 21.1% categories. If any organization wants to enter into app making business then first they need a strong analysis on the existing data to understand the requirements and to understand the market. From analysis I found out that teen agers use the apps most so they are the targeting market for normal apps. On basis of chart 12 and other few more charts according to me Gaming apps are used more by our majority of the market that is teen agers and they can be more charged compared to other category apps. The organization can create other category apps also but they need this type of analysis to go and invest further in the app making business.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""

